# Bloc 3 — Transformations & Feature Engineering
Objectifs: créer des colonnes calculées, transformer les types, manipuler les chaînes (.str), manipuler les dates (.dt), trier

In [1]:
import numpy as np
import pandas as pd

In [2]:
products = pd.read_csv('../01_data/raw/thelook_products.csv')
sales = pd.read_csv('../01_data/exercises/thelook_sales.csv')
orders = pd.read_csv('../01_data/raw/thelook_orders.csv')

## 1. Ajouter et modifier des colonnes
On travaille souvent avec des colonnes qui n'existent pas encore dans le dataset. Il faut les créer.

### Créer une colonne calculée

In [3]:
products['marge'] = products['retail_price'] - products['cost']

# la nouvelle colonne apparait à droite
products.head()

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id,marge
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Tommy Hilfiger,Women,6.57,10.31,SKU-00001,5,3.74
1,2,Hurley Pro Shorts,Shorts,Hurley,Women,20.85,37.55,SKU-00002,6,16.70
2,3,Columbia Sport Tops & Tees,Tops & Tees,Columbia,Men,21.34,44.52,SKU-00003,9,23.18
3,4,Volcom Classic Leggings,Leggings,Volcom,Women,14.98,42.24,SKU-00004,2,27.26
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Hurley,Women,89.58,149.11,SKU-00005,5,59.53

### Renommer ajouter et supprimer des colonnes

In [4]:
# imaginer que le nom des colomnes n'arriveront jamais bien formatés. 
# Une bonne pratique en base de donné et dataset est d'utiliser le snake_case
products = products.rename(columns={'retail_price': 'retail_price_euro'})
products = products.rename(columns={'sku': 'reference'})
products.head()

,id,name,category,brand,department,cost,retail_price_euro,reference,distribution_center_id,marge
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Tommy Hilfiger,Women,6.57,10.31,SKU-00001,5,3.74
1,2,Hurley Pro Shorts,Shorts,Hurley,Women,20.85,37.55,SKU-00002,6,16.70
2,3,Columbia Sport Tops & Tees,Tops & Tees,Columbia,Men,21.34,44.52,SKU-00003,9,23.18
3,4,Volcom Classic Leggings,Leggings,Volcom,Women,14.98,42.24,SKU-00004,2,27.26
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Hurley,Women,89.58,149.11,SKU-00005,5,59.53

In [5]:
# Mais il vous sera aussi nécessaire de créer vos propres colonnes
# Ici, on change également le type
products['ref_id'] = products['reference'] + products['id'].astype(str)
products.info()

# Pourquoi doit-on caster le type de la colonne ['id']? 
# Essayer sans pour voir...

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      2000 non-null   int64
 1   name                    2000 non-null   str
 2   category                2000 non-null   str
 3   brand                   2000 non-null   str
 4   department              2000 non-null   str
 5   cost                    2000 non-null   float64
 6   retail_price_euro       2000 non-null   float64
 7   reference               2000 non-null   str
 8   distribution_center_id  2000 non-null   int64
 9   marge                   2000 non-null   float64
 10  ref_id                  2000 non-null   str
dtypes: float64(3), int64(2), str(6)
memory usage: 172.0 KB

In [6]:
# Il peut aussi arriver que vous deviez supprimer des colonnes inutiles ou pour créer un dataset alternatif
products = products.drop(columns=['brand'])
products.head()

,id,name,category,department,cost,retail_price_euro,reference,distribution_center_id,marge,ref_id
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Women,6.57,10.31,SKU-00001,5,3.74,SKU-000011
1,2,Hurley Pro Shorts,Shorts,Women,20.85,37.55,SKU-00002,6,16.70,SKU-000022
2,3,Columbia Sport Tops & Tees,Tops & Tees,Men,21.34,44.52,SKU-00003,9,23.18,SKU-000033
3,4,Volcom Classic Leggings,Leggings,Women,14.98,42.24,SKU-00004,2,27.26,SKU-000044
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Women,89.58,149.11,SKU-00005,5,59.53,SKU-000055

In [7]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      2000 non-null   int64
 1   name                    2000 non-null   str
 2   category                2000 non-null   str
 3   department              2000 non-null   str
 4   cost                    2000 non-null   float64
 5   retail_price_euro       2000 non-null   float64
 6   reference               2000 non-null   str
 7   distribution_center_id  2000 non-null   int64
 8   marge                   2000 non-null   float64
 9   ref_id                  2000 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 156.4 KB

### Mini-exercice : à vous !

In [12]:
# Créez une colonne 'taux_marge' = marge / retail_price * 100
 products['taux_marge'] = products['marge'] / products['retail_price'] * 100
 products['taux_marge'].head(3)
# Affichez les 3 premières lignes

IndentationError: unexpected indent (668922331.py, line 2)

## 2. Transformer les types (dtypes)
Quand on charge un CSV, pandas devine les types. Parfois il se trompe. Il faut savoir corriger.

### Vérifier les types actuels

In [ ]:
# Que remarquez-vous sur created_at ?
print(orders.dtypes)

### Convertir avec .astype()

Nous avons vu précédemment que Python possède ses propres fonction pour changer le type de data dúne variable.Pandas a sa propre méthode pour se faire: `.astype()`

In [60]:
print("Avant :", products['id'].dtype)
products['id'] = products['id'].astype(str)
print("Après :", products['id'].dtype)

Avant : int64
Après : str

### Forcer la conversion numérique : pd.to_numeric()

In [13]:
s = pd.Series(['10', '20', 'oops', '40'])
s.info()

<class 'pandas.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: None
Non-Null Count  Dtype
--------------  -----
4 non-null      str
dtypes: str(1)
memory usage: 164.0 bytes

In [14]:
# Pour transformer nos strings, on utilise la fonction pd.to_numeric()
# errors='coerce' transforme les erreurs en NaN au lieu de planter
s_numeric = pd.to_numeric(s, errors='coerce')
s_numeric

0    10.0
1    20.0
2     NaN
3    40.0
dtype: float64

### Convertir les dates : pd.to_datetime()

In [15]:
# On va utiliser ici le dataset `orders` que vous avez chargé plus tôt.
# Observons son data type:

#orders.

# Quel est le type de delivered_at? returned_at?

In [114]:
# Ceci est un cas typique où vous aurez des datetime ou des timestamps qui arriveront sous forme d'objets ou string.
orders['created_at'] = pd.to_datetime(orders['created_at'])

print(orders['created_at'].dtype)  # on doit trouver: datetime64
orders.info()

datetime64[us]
<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  int64
 1   user_id       20000 non-null  int64
 2   status        20000 non-null  str
 3   created_at    20000 non-null  datetime64[us]
 4   num_of_item   20000 non-null  int64
 5   shipped_at    16800 non-null  str
 6   delivered_at  14361 non-null  str
 7   returned_at   1388 non-null   str
dtypes: datetime64[us](1), int64(3), str(4)
memory usage: 1.2 MB

## 3. Manipuler le texte avec .str
Pandas offre un accesseur `.str` qui permet d'appliquer des opérations texte à toute une colonne d'un coup.

### Changer le format

In [23]:
# tout en minuscules, le plus souvent utilisé dans le code. Qui aime se faire hurler dessus en capitale par son code?
lower = products['name'].str.lower().head(3)
lower

0    tommy hilfiger regular fit underwear
1                       hurley pro shorts
2              columbia sport tops & tees
Name: name, dtype: str

In [24]:
# ici en MAJUSCULE
upper = products['name'].str.upper().head(3)
upper

0    TOMMY HILFIGER REGULAR FIT UNDERWEAR
1                       HURLEY PRO SHORTS
2              COLUMBIA SPORT TOPS & TEES
Name: name, dtype: str

In [25]:
# Et Là ?
title = products['name'].str.title().head(3)
title

0    Tommy Hilfiger Regular Fit Underwear
1                       Hurley Pro Shorts
2              Columbia Sport Tops & Tees
Name: name, dtype: str

### Chercher dans le texte

In [27]:
# Combien de produits contiennent le mot 'Slim' ?
slim = products['name'].str.contains(('Slim'), na=False)
print(slim.sum())

# Et si je ne sais pas si j'ai SLIM, Slim, ou slim ?

161

### Nettoyer le texte

In [20]:
# Explique que fait on ici:
nettoye = products['name'].str.strip().str.replace('  ', '')
nettoye.head()

0    Tommy Hilfiger Regular Fit Underwear
1                       Hurley Pro Shorts
2              Columbia Sport Tops & Tees
3                 Volcom Classic Leggings
4          Hurley Urban Outerwear & Coats
Name: name, dtype: str

## 4. Manipuler les dates avec .dt

### Extraire les composantes d'une date
Par défaut, lors de la lecture d'un fichier (ex: CSV), Pandas importe les dates sous forme de simples chaînes de caractères (object ou str).

Sous forme de texte, vous ne pouvez pas:
- effectuer de calculs temporels 
- extraire facilement des composants de date (example: jour, mois etc...)

Une fois la colonne convertie en datetime, on peut en extraire plein d'informations.

In [22]:
# Chaque composante devient une nouvelle colonne utilisable pour l'analyse

orders['annee'] = orders['created_at'].dt.year
orders['mois'] = orders['created_at'].dt.month
orders['jour_semaine'] = orders['created_at'].dt.day_name()
orders.head()

AttributeError: Can only use .dt accessor with datetimelike values

In [28]:
# Vérifiez le type des nouvelles colonnes créées
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  int64
 1   user_id       20000 non-null  int64
 2   status        20000 non-null  str
 3   created_at    20000 non-null  str
 4   num_of_item   20000 non-null  int64
 5   shipped_at    16800 non-null  str
 6   delivered_at  14361 non-null  str
 7   returned_at   1388 non-null   str
dtypes: int64(3), str(5)
memory usage: 1.2 MB

### Calculer un écart entre deux dates

In [29]:
# Rappel de conversion str -> datetime type
orders['shipped_at'] = pd.to_datetime(orders['shipped_at'])

# Le résultat est un timedelta, .dt.days donne le nombre de jours
# on peut utiliser de simple operator comme '-' ou '+'
orders['delai'] = (orders['shipped_at'] - orders['created_at']).dt.days

orders[['created_at', 'shipped_at', 'delai']].head()

C:\Users\loic\AppData\Local\Temp\ipykernel_8540\2017459241.py:6: PerformanceWarning: Adding/subtracting object-dtype array to DatetimeArray not vectorized.
  orders['delai'] = (orders['shipped_at'] - orders['created_at']).dt.days

TypeError: unsupported operand type(s) for -: 'Timestamp' and 'str'

# Quel est le délai de livraison moyen ? Testez avec .mean()

In [30]:
delai_moyen = orders['delai']."METHODE"()
print(delai_moyen)

SyntaxError: invalid syntax (3634597158.py, line 1)

## 5. Trier les données

### Trier par valeurs

In [31]:
# Selon vous, que fait cette fonction? A quoi correspond l'argument 'ascending'
products.sort_values('retail_price', ascending=False).head(10)

KeyError: 'retail_price'

### Trier par plusieurs colonnes

In [123]:
products.sort_values(['department', 'retail_price'], ascending=[True, False]).head(10)

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id
1787,1788,Dockers Premium Suits & Sport Coats,Suits & Sport Coats,Dockers,Men,168.68,484.08,SKU-01788,5
600,601,Levi's Classic Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,194.24,472.27,SKU-00601,8
1247,1248,BCBGMAXAZRIA Sport Suits & Sport Coats,Suits & Sport Coats,BCBGMAXAZRIA,Men,171.50,468.52,SKU-01248,8
298,299,Allegra K Vintage Suits & Sport Coats,Suits & Sport Coats,Allegra K,Men,191.39,462.85,SKU-00299,9
1977,1978,Diesel Modern Suits & Sport Coats,Suits & Sport Coats,Diesel,Men,172.04,461.81,SKU-01978,1
1489,1490,Tommy Hilfiger Original Suits & Sport Coats,Suits & Sport Coats,Tommy Hilfiger,Men,168.12,454.79,SKU-01490,10
142,143,Levi's Sport Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,153.02,446.66,SKU-00143,9
440,441,True Religion Regular Fit Suits & Sport Coats,Suits & Sport Coats,True Religion,Men,167.97,446.63,SKU-00441,2
211,212,Hurley Slim Fit Outerwear & Coats,Outerwear & Coats,Hurley,Men,141.69,413.60,SKU-00212,9
212,213,Volcom Slim Fit Outerwear & Coats,Outerwear & Coats,Volcom,Men,147.98,404.95,SKU-00213,3

### Réinitialiser l'index

In [124]:
# Après un tri ou un filtre, l'index est désorganisé. reset_index le remet à 0, 1, 2...
produits_tries = products.sort_values('retail_price', ascending=False)
produits_tries.reset_index(drop=True).head()

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id
0,1494,Hurley Essential Suits & Sport Coats,Suits & Sport Coats,Hurley,Women,198.17,512.19,SKU-01494,5
1,1788,Dockers Premium Suits & Sport Coats,Suits & Sport Coats,Dockers,Men,168.68,484.08,SKU-01788,5
2,601,Levi's Classic Suits & Sport Coats,Suits & Sport Coats,Levi's,Men,194.24,472.27,SKU-00601,8
3,1248,BCBGMAXAZRIA Sport Suits & Sport Coats,Suits & Sport Coats,BCBGMAXAZRIA,Men,171.50,468.52,SKU-01248,8
4,299,Allegra K Vintage Suits & Sport Coats,Suits & Sport Coats,Allegra K,Men,191.39,462.85,SKU-00299,9

---
# Exercices pratiques

## Exercice 3.1 — L'Ingénieur de Features

### Questions
- Comment définissez vous le terme "features" ?
- Citez au moins 2 examples de features dont vous pouvez vous servir lors de la manipulation d'un dataset

### Pratique
Chargez `../01_data/exercises/thelook_sales.csv`. Créez ces colonnes:
1. `marge` = sale_price - cost
2. `mois` extrait de created_at (convertissez d'abord en datetime)
3. `is_premium` = True si sale_price > 100
4. `taux_marge` = (marge / sale_price) * 100

In [37]:
# 1. Chargez le fichier et créez les colonnes marge et taux_marge
ventes = pd.read_csv('../01_data/exercises/thelook_sales.csv')
ventes.head()

,id,order_id,user_id,product_id,sale_price,status,created_at,shipped_at,delivered_at,returned_at,product_name,category,brand,department,cost,gender,age,country,city,traffic_source
0,1,2006,3641,533,37.47,Complete,2023-05-24 05:04:44,2023-05-25 05:04:44,2023-05-30 05:04:44,NaN,Volcom Pro Active,Active,Volcom,Women,27.45,F,27,Australia,Perth,Search
1,2,19606,4289,1234,41.01,Complete,2024-06-14 02:09:32,2024-06-16 02:09:32,2024-06-19 02:09:32,NaN,Volcom Modern Shorts,Shorts,Volcom,Men,23.79,M,39,Mexico,Guadalajara,Search
2,3,14234,973,409,15.67,Complete,2023-06-16 03:42:36,2023-06-17 03:42:36,2023-06-25 03:42:36,NaN,Adidas Modern Socks & Hosiery,Socks & Hosiery,Adidas,Men,8.97,F,45,Poland,Warsaw,Search
3,4,14616,2136,67,75.15,Complete,2024-12-01 13:36:46,2024-12-03 13:36:46,2024-12-08 13:36:46,NaN,Under Armour Regular Fit Jumpsuits & Rompers,Jumpsuits & Rompers,Under Armour,Men,37.25,M,36,Spain,Seville,Organic
4,5,7423,4007,1882,18.20,Complete,2024-08-21 13:24:24,2024-08-22 13:24:24,2024-08-29 13:24:24,NaN,Hurley Modern Skirts,Skirts,Hurley,Women,14.42,F,40,United Kingdom,Manchester,Organic

In [39]:
# Ajout de la colonne marge
ventes['marge'] = ventes['sale_price'] - ventes['cost']
ventes.head()

,id,order_id,user_id,product_id,sale_price,status,created_at,shipped_at,delivered_at,returned_at,...,category,brand,department,cost,gender,age,country,city,traffic_source,marge
0,1,2006,3641,533,37.47,Complete,2023-05-24 05:04:44,2023-05-25 05:04:44,2023-05-30 05:04:44,NaN,...,Active,Volcom,Women,27.45,F,27,Australia,Perth,Search,10.02
1,2,19606,4289,1234,41.01,Complete,2024-06-14 02:09:32,2024-06-16 02:09:32,2024-06-19 02:09:32,NaN,...,Shorts,Volcom,Men,23.79,M,39,Mexico,Guadalajara,Search,17.22
2,3,14234,973,409,15.67,Complete,2023-06-16 03:42:36,2023-06-17 03:42:36,2023-06-25 03:42:36,NaN,...,Socks & Hosiery,Adidas,Men,8.97,F,45,Poland,Warsaw,Search,6.70
3,4,14616,2136,67,75.15,Complete,2024-12-01 13:36:46,2024-12-03 13:36:46,2024-12-08 13:36:46,NaN,...,Jumpsuits & Rompers,Under Armour,Men,37.25,M,36,Spain,Seville,Organic,37.90
4,5,7423,4007,1882,18.20,Complete,2024-08-21 13:24:24,2024-08-22 13:24:24,2024-08-29 13:24:24,NaN,...,Skirts,Hurley,Women,14.42,F,40,United Kingdom,Manchester,Organic,3.78

In [40]:
# ajout de la colonne is_premium
ventes['is_premium'] = ventes['sale_price'] > 100
ventes.head()

,id,order_id,user_id,product_id,sale_price,status,created_at,shipped_at,delivered_at,returned_at,...,brand,department,cost,gender,age,country,city,traffic_source,marge,is_premium
0,1,2006,3641,533,37.47,Complete,2023-05-24 05:04:44,2023-05-25 05:04:44,2023-05-30 05:04:44,NaN,...,Volcom,Women,27.45,F,27,Australia,Perth,Search,10.02,False
1,2,19606,4289,1234,41.01,Complete,2024-06-14 02:09:32,2024-06-16 02:09:32,2024-06-19 02:09:32,NaN,...,Volcom,Men,23.79,M,39,Mexico,Guadalajara,Search,17.22,False
2,3,14234,973,409,15.67,Complete,2023-06-16 03:42:36,2023-06-17 03:42:36,2023-06-25 03:42:36,NaN,...,Adidas,Men,8.97,F,45,Poland,Warsaw,Search,6.70,False
3,4,14616,2136,67,75.15,Complete,2024-12-01 13:36:46,2024-12-03 13:36:46,2024-12-08 13:36:46,NaN,...,Under Armour,Men,37.25,M,36,Spain,Seville,Organic,37.90,False
4,5,7423,4007,1882,18.20,Complete,2024-08-21 13:24:24,2024-08-22 13:24:24,2024-08-29 13:24:24,NaN,...,Hurley,Women,14.42,F,40,United Kingdom,Manchester,Organic,3.78,False

In [44]:
# Ajout colonne taux_marge
ventes['taux_marge'] = ((ventes['marge'] / ventes['sale_price']) * 100).round(2)
ventes.head()

,id,order_id,user_id,product_id,sale_price,status,created_at,shipped_at,delivered_at,returned_at,...,department,cost,gender,age,country,city,traffic_source,marge,is_premium,taux_marge
0,1,2006,3641,533,37.47,Complete,2023-05-24 05:04:44,2023-05-25 05:04:44,2023-05-30 05:04:44,NaN,...,Women,27.45,F,27,Australia,Perth,Search,10.02,False,26.74
1,2,19606,4289,1234,41.01,Complete,2024-06-14 02:09:32,2024-06-16 02:09:32,2024-06-19 02:09:32,NaN,...,Men,23.79,M,39,Mexico,Guadalajara,Search,17.22,False,41.99
2,3,14234,973,409,15.67,Complete,2023-06-16 03:42:36,2023-06-17 03:42:36,2023-06-25 03:42:36,NaN,...,Men,8.97,F,45,Poland,Warsaw,Search,6.70,False,42.76
3,4,14616,2136,67,75.15,Complete,2024-12-01 13:36:46,2024-12-03 13:36:46,2024-12-08 13:36:46,NaN,...,Men,37.25,M,36,Spain,Seville,Organic,37.90,False,50.43
4,5,7423,4007,1882,18.20,Complete,2024-08-21 13:24:24,2024-08-22 13:24:24,2024-08-29 13:24:24,NaN,...,Women,14.42,F,40,United Kingdom,Manchester,Organic,3.78,False,20.77

In [ ]:
# 2. Convertissez created_at et extrayez le mois
# Votre code ici

In [ ]:
# 3. Créez is_premium et affichez le pourcentage de ventes premium
# Votre code ici

## Exercice 3.2 — Le Nettoyeur de Noms
Chargez `../01_data/raw/thelook_products.csv`.
1. Mettez la colonne `name` en title case
2. Extrayez le premier mot du nom dans une colonne `marque`
3. Combien de produits contiennent le mot 'Slim' ?

In [ ]:
# 1 et 2. Title case + extraction marque
products = pd.read_csv('../01_data/raw/thelook_products.csv')
# mettre les noms de produits en title case 
products['name'] = products['name'].str.title()

In [ ]:
# nombre de produits contenant le mot 'Slim' 
nb_produits_slim = products['name'].str.contains('Slim').sum()
print(f"Nombre de produits contenant le mot 'Slim' : {nb_produits_slim}")

Nombre de produits contenant le mot 'Slim' : 161

In [ ]:
# 3. Comptez les produits 'Sport'
# Votre code ici

## Exercice 3.3 — L'analyse temporel
Chargez `../01_data/raw/thelook_orders.csv`.
1. Convertissez created_at, shipped_at, delivered_at en datetime
2. Créez `delai_livraison` = delivered_at - created_at (en jours)
3. Quel est le délai moyen ? Varie-t-il selon le jour de la semaine ?

In [ ]:
# 1. Conversion des dates
# Votre code ici

In [ ]:
# 2. Calcul du délai
# Votre code ici

In [ ]:
# 3. Délai moyen et variation par jour
# Votre code ici