# 🏋️ Exercice Intégrateur — L'Analyste Junior (Préparation Examen)

Vous venez d'être embauché(e) comme Junior Data Analyst chez TheLook, une boutique de mode en ligne.
Votre manager vous confie un premier fichier de ventes et attend un rapport d'exploration complet.

> 💡 **Note:** Cet exercice est la version guidée et concentrée de ce qui vous attend cet après-midi pour votre projet final (qui servira d'examen). 
> Profitez de cette session (1h15) pour valider vos acquis : chargement, exploration, **nettoyage**, filtrage, transformation et statistiques descriptives.

In [1]:
import numpy as np
import pandas as pd

## Étape 1 : Charger & Explorer
Chargez le fichier des ventes et produisez un rapport d'exploration complet.

In [5]:
# Chargez le dataset (utilisez la version 'dirty' pour vous entraîner au nettoyage)
sales = pd.read_csv('../01_data/exercises/thelook_sales_dirty.csv')

In [6]:
# Combien de lignes et colonnes ?
nombre_lignes_colones = sales.shape
nombre_lignes_colones

(51000, 20)

In [7]:
# Quels sont les types de chaque colonne ? (une seule commande)
sales.dtypes

id                  int64
order_id            int64
user_id             int64
product_id          int64
sale_price        float64
status                str
created_at            str
shipped_at            str
delivered_at          str
returned_at           str
product_name          str
category              str
brand                 str
department            str
cost                  str
gender                str
age               float64
country               str
city                  str
traffic_source        str
dtype: object

In [10]:
# Y a-t-il des valeurs manquantes ? (une seule commande)
sales.isna().sum()

id                    0
order_id              0
user_id               0
product_id            0
sale_price         4039
status                0
created_at            0
shipped_at         8038
delivered_at      14345
returned_at       47403
product_name          0
category           6720
brand                 0
department            0
cost                  0
gender                0
age                2502
country               0
city                  0
traffic_source        0
dtype: int64

## Étape 1.5 : Nettoyer les données
Votre exploration a révélé des problèmes. Avant de faire des statistiques, il faut s'assurer que les données sont propres.

In [14]:
# Traitez les valeurs manquantes (imputez ou supprimez en justifiant votre choix en commentaire)
sales_clean = sales.copy()
# Suppression des lignes avec des valeurs manquantes
sales_clean = sales_clean.dropna()

In [13]:
sales_clean.isna().sum()  # Vérification des valeurs manquantes après le nettoyage

id                0
order_id          0
user_id           0
product_id        0
sale_price        0
status            0
created_at        0
shipped_at        0
delivered_at      0
returned_at       0
product_name      0
category          0
brand             0
department        0
cost              0
gender            0
age               0
country           0
city              0
traffic_source    0
dtype: int64

In [ ]:
# Vérifiez et supprimez les doublons exacts s'il y en a
sales_clean = sales_clean.drop_duplicates()

(2687, 20)

In [18]:
# verification du nombre de lignes et colonnes après le nettoyage
sales_clean.shape

(2687, 20)

In [ ]:
# Standardisez une colonne texte (ex: mettez les noms de pays en minuscules et sans espaces autour pour vérifier la propreté)
sales_clean['country'] = sales_clean['country'].str.strip().str.lower()

42             belgium
45       united states
49              mexico
61             germany
77              poland
             ...
50749           mexico
50776    united states
50797    united states
50952            spain
50957        australia
Name: country, Length: 2687, dtype: str

In [ ]:
# j'affiche les valeurs de la colonne 'country' pour vérifier la standardisation
sales_clean['country']

## Étape 2 : Filtrer
Votre manager s'intéresse uniquement au département **Women** et aux ventes de l'année la plus récente.

In [ ]:
# Convertissez created_at en datetime
sales_clean['created_at'] = pd.to_datetime(sales_clean['created_at'], errors='coerce')

np.int32(2024)

In [ ]:
# Trouvez l'année la plus récente
latest_year = sales_clean['created_at'].dt.year.max()
latest_year

In [27]:
# Appliquez le double filtre (women department & annee la plus récente)
sales_filtered = sales_clean[(sales_clean['department'] == 'Women') & (sales_clean['created_at'].dt.year == latest_year)]
sales_filtered

,id,order_id,user_id,product_id,sale_price,status,created_at,shipped_at,delivered_at,returned_at,product_name,category,brand,department,cost,gender,age,country,city,traffic_source
45,46,5091,1046,283,68.80,Returned,2024-08-02 02:58:14,2024-08-04 02:58:14,2024-08-07 02:58:14,2024-09-04 02:58:14,Carhartt Comfort Jumpsuits & Rompers,Jumpsuits & Rompers,Carhartt,Women,$34.14,M,34.0,united states,Phoenix,Organic
95,96,387,942,1515,243.55,Returned,2024-06-02 09:57:41,2024-06-05 09:57:41,2024-06-08 09:57:41,2024-06-14 09:57:41,Carhartt Pro Suits & Sport Coats,Suits & Sport Coats,Carhartt,Women,$166.80,F,45.0,united states,Houston,Facebook
190,191,16896,1557,1193,39.72,Returned,2024-02-20 09:42:18,2024-02-23 09:42:18,2024-02-28 09:42:18,2024-03-17 09:42:18,Carhartt Comfort Fashion Hoodies & Sweatshirts,Fashion Hoodies & Sweatshirts,Carhartt,Women,$21.23,M,23.0,spain,Barcelona,Email
212,213,18111,790,1515,207.22,Returned,2024-11-04 02:03:59,2024-11-07 02:03:59,2024-11-12 02:03:59,2024-11-27 02:03:59,Carhartt Pro Suits & Sport Coats,Suits & Sport Coats,Carhartt,Women,$166.80,F,48.0,u.s.a.,Houston,Search
241,242,15966,772,646,93.60,Returned,2024-05-19 19:51:07,2024-05-20 19:51:07,2024-05-26 19:51:07,2024-06-13 19:51:07,Allegra K Vintage Skirts,Skirts,Allegra K,Women,$36.36,M,34.0,australia,Brisbane,Facebook
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50189,46365,3242,4617,530,52.20,Returned,2024-12-17 22:30:44,2024-12-19 22:30:44,2024-12-25 22:30:44,2024-12-31 22:30:44,Lucky Brand Premium Swim,Swim,Lucky Brand,Women,$26.71,M,46.0,china,Chengdu,Organic
50401,41390,18323,2977,492,177.05,Returned,2024-04-13 09:56:35,2024-04-15 09:56:35,2024-04-18 09:56:35,2024-05-18 09:56:35,Polo Ralph Lauren Premium Suits & Sport Coats,Suits & Sport Coats,Polo Ralph Lauren,Women,$77.13,M,23.0,australia,Brisbane,Search
50697,45344,5318,1682,1866,127.41,Returned,2024-09-14 08:24:02,2024-09-16 08:24:02,2024-09-19 08:24:02,2024-10-03 08:24:02,Volcom Sport Jumpsuits & Rompers,Jumpsuits & Rompers,Volcom,Women,$46.81,F,26.0,united states,Los Angeles,Facebook
50701,37196,16170,1979,1054,89.32,Returned,2024-02-15 18:01:48,2024-02-17 18:01:48,2024-02-22 18:01:48,2024-03-10 18:01:48,Nike Slim Fit Sweaters,Sweaters,Nike,Women,$50.97,F,29.0,united states,New York,Organic
50957,4230,10532,3675,913,50.26,Returned,2024-07-23 08:22:13,2024-07-25 08:22:13,2024-07-31 08:22:13,2024-08-10 08:22:13,Carhartt Classic Tops & Tees,Tops & Tees,Carhartt,Women,$24.60,M,44.0,australia,Perth,Facebook

## Étape 3 : Transformer
Sur le sous-ensemble filtré, créez les colonnes suivantes :

In [29]:
sales_filtered.dtypes  # Vérification des types de colonnes après le filtrage

id                         int64
order_id                   int64
user_id                    int64
product_id                 int64
sale_price               float64
status                       str
created_at        datetime64[us]
shipped_at                   str
delivered_at                 str
returned_at                  str
product_name                 str
category                     str
brand                        str
department                   str
cost                         str
gender                       str
age                      float64
country                      str
city                         str
traffic_source               str
dtype: object

In [31]:
# Créez 'marge_pct' = (sale_price - cost) / sale_price * 100
sales_filtered['marge_pct'] = (sales_filtered['sale_price'] - sales_filtered['cost'].str.replace('$', '').astype(float)) / sales_filtered['sale_price'] * 100

sales_filtered

,id,order_id,user_id,product_id,sale_price,status,created_at,shipped_at,delivered_at,returned_at,...,category,brand,department,cost,gender,age,country,city,traffic_source,marge_pct
45,46,5091,1046,283,68.80,Returned,2024-08-02 02:58:14,2024-08-04 02:58:14,2024-08-07 02:58:14,2024-09-04 02:58:14,...,Jumpsuits & Rompers,Carhartt,Women,$34.14,M,34.0,united states,Phoenix,Organic,50.377907
95,96,387,942,1515,243.55,Returned,2024-06-02 09:57:41,2024-06-05 09:57:41,2024-06-08 09:57:41,2024-06-14 09:57:41,...,Suits & Sport Coats,Carhartt,Women,$166.80,F,45.0,united states,Houston,Facebook,31.513036
190,191,16896,1557,1193,39.72,Returned,2024-02-20 09:42:18,2024-02-23 09:42:18,2024-02-28 09:42:18,2024-03-17 09:42:18,...,Fashion Hoodies & Sweatshirts,Carhartt,Women,$21.23,M,23.0,spain,Barcelona,Email,46.550856
212,213,18111,790,1515,207.22,Returned,2024-11-04 02:03:59,2024-11-07 02:03:59,2024-11-12 02:03:59,2024-11-27 02:03:59,...,Suits & Sport Coats,Carhartt,Women,$166.80,F,48.0,u.s.a.,Houston,Search,19.505839
241,242,15966,772,646,93.60,Returned,2024-05-19 19:51:07,2024-05-20 19:51:07,2024-05-26 19:51:07,2024-06-13 19:51:07,...,Skirts,Allegra K,Women,$36.36,M,34.0,australia,Brisbane,Facebook,61.153846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50189,46365,3242,4617,530,52.20,Returned,2024-12-17 22:30:44,2024-12-19 22:30:44,2024-12-25 22:30:44,2024-12-31 22:30:44,...,Swim,Lucky Brand,Women,$26.71,M,46.0,china,Chengdu,Organic,48.831418
50401,41390,18323,2977,492,177.05,Returned,2024-04-13 09:56:35,2024-04-15 09:56:35,2024-04-18 09:56:35,2024-05-18 09:56:35,...,Suits & Sport Coats,Polo Ralph Lauren,Women,$77.13,M,23.0,australia,Brisbane,Search,56.436035
50697,45344,5318,1682,1866,127.41,Returned,2024-09-14 08:24:02,2024-09-16 08:24:02,2024-09-19 08:24:02,2024-10-03 08:24:02,...,Jumpsuits & Rompers,Volcom,Women,$46.81,F,26.0,united states,Los Angeles,Facebook,63.260341
50701,37196,16170,1979,1054,89.32,Returned,2024-02-15 18:01:48,2024-02-17 18:01:48,2024-02-22 18:01:48,2024-03-10 18:01:48,...,Sweaters,Nike,Women,$50.97,F,29.0,united states,New York,Organic,42.935513
50957,4230,10532,3675,913,50.26,Returned,2024-07-23 08:22:13,2024-07-25 08:22:13,2024-07-31 08:22:13,2024-08-10 08:22:13,...,Tops & Tees,Carhartt,Women,$24.60,M,44.0,australia,Perth,Facebook,51.054517

In [32]:
# Extrayez le mois de created_at dans une colonne 'mois'
sales_filtered['mois'] = sales_filtered['created_at'].dt.month

sales_filtered['mois']

45        8
95        6
190       2
212      11
241       5
         ..
50189    12
50401     4
50697     9
50701     2
50957     7
Name: mois, Length: 721, dtype: int32

In [39]:
# Créez 'categorie_prix' : 'Budget' (<25), 'Mid-range' (25-75), 'Premium' (>75)
sales_filtered['categorie_prix'] = pd.cut(sales_filtered['sale_price'], bins=[0, 25, 75, float('inf')], labels=['Budget', 'Mid-range', 'Premium'])
sales_filtered['categorie_prix']

45       Mid-range
95         Premium
190      Mid-range
212        Premium
241        Premium
           ...
50189    Mid-range
50401      Premium
50697      Premium
50701      Premium
50957    Mid-range
Name: categorie_prix, Length: 721, dtype: category
Categories (3, str): ['Budget' < 'Mid-range' < 'Premium']

## Étape 4 : Statistiques descriptives
Répondez à ces 5 questions sur vos données filtrées :

In [35]:
# Q1 : Quelle est la moyenne et la médiane de sale_price ?
mean_sale_price = sales_filtered['sale_price'].mean().round(2)
median_sale_price = sales_filtered['sale_price'].median()
mean_sale_price, median_sale_price

(np.float64(112.61), np.float64(43.8))

In [36]:
# Q2 : Quelles sont les 5 catégories avec le plus de ventes ?
sales_filtered.groupby('categorie_prix').size().sort_values(ascending=False).head(5)

categorie_prix
Mid-range    354
Budget       183
Premium      183
dtype: int64

In [ ]:
# Q3 : Quel mois a le plus de ventes ?
# Votre code ici

In [ ]:
# Q4 : Quelle est la marge moyenne par catégorie de prix ?
# Votre code ici

In [ ]:
# Q5 : Quelle est la répartition des sources de trafic ?
# Votre code ici

## Bonus : Visualisation
Créez au moins un graphique avec `.plot()` pour illustrer une de vos analyses.

In [ ]:
# Votre visualisation ici
# Astuce : .value_counts().plot(kind='bar')